baseURL = "zhengxixuan.com"
languageCode = "zh-cn"
title = "DesignYourself"
theme = "cactus"
copyright = "郑嘻嘻"
disqusShortname = "zhengxixuan" 
googleAnalytics = "UA-106973310-1"



# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "喜欢番茄  喜欢橙子  喜欢晒太阳  喜欢三文鱼  喜欢Negroni"
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/zhengxixuan" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = true # default
    engine = "disqus" # more supported engines will be added.

  rss = true

  mathjax = true  # not required

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/zhengxixuan"
  [[params.social]]
    name = "twitter"
    link = "https://www.twitter.com/zhengxixuan"
  [[params.social]]
    name = "email"
    link = "xixuanzheng@163.com"  # no need for "mailto:" in the head